/* ============================================================
   KWCAG 2.2 검사항목 33개

   한국형 웹 콘텐츠 접근성 지침 2.2 는 4개 원칙, 14개 지침, 33개 검사항목으로
   구성되며 **A·AA·AAA 등급을 사용하지 않는다.** 그래서 이 데이터셋은
   level 이 전부 null 이고, KWCAG 모드는 33개 전체를 생성한다.

   `title` 은 표준의 공식 항목명을 쓰고, `question` 은 실무자가 답할 수 있는
   별도 문장으로 다시 쓴다. 공식 설명 전체를 복제하지 않는다.
   ============================================================ */
import { SOURCES, type ChecklistDefinition } from "./types";

const src = SOURCES.kwcag;

export const KWCAG_ITEMS: ChecklistDefinition[] = [
  {
    id: "kwcag-1",
    standard: "kwcag-2.2",
    criterion: "1",
    level: null,
    title: { ko: "적절한 대체 텍스트 제공", en: "Appropriate alternative text" },
    question: {
      ko: "의미를 전달하는 모든 이미지·아이콘·차트에 그 맥락에 맞는 대체 텍스트가 있나요?",
      en: "Does every meaningful image, icon, and chart have a text alternative that fits its context?",
    },
    howToCheck: {
      ko: [
        "화면의 이미지를 정보 전달용·장식용·기능(버튼·링크)용으로 나눕니다.",
        "정보 전달용은 이미지가 가진 정보를, 기능용은 수행할 동작을 alt 로 적었는지 확인합니다.",
        "장식용 이미지는 alt=\"\" 또는 CSS 배경으로 처리해 보조기술이 읽지 않게 합니다.",
        "차트·인포그래픽처럼 정보가 많은 이미지는 본문이나 표로 같은 정보를 제공했는지 확인합니다.",
      ],
      en: [
        "Sort the images on screen into informative, decorative, and functional (button or link) roles.",
        "Confirm informative images describe the information and functional images describe the action.",
        "Mark decorative images with an empty alt or move them to CSS backgrounds.",
        "For charts and infographics, confirm the same information exists as text or a table.",
      ],
    },
    evidence: {
      ko: "검토한 화면, 이미지 분류 기준, 수정한 alt 문구 목록을 메모에 남깁니다.",
      en: "Record the screens reviewed, how images were classified, and the alt text you changed.",
    },
    axis: "structure-semantics",
    roles: ["planning", "publishing"],
    phases: ["design", "implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "html-accessibility-checker",
  },
  {
    id: "kwcag-2",
    standard: "kwcag-2.2",
    criterion: "2",
    level: null,
    title: { ko: "자막 제공", en: "Captions" },
    question: {
      ko: "동영상·음성 콘텐츠에 자막, 원고 또는 수어 중 하나 이상을 제공하나요?",
      en: "Does every video or audio item provide captions, a transcript, or sign language?",
    },
    howToCheck: {
      ko: [
        "서비스에 올라간 녹화 영상·음성과 실시간 방송 목록을 모읍니다.",
        "자동 생성 자막에 의존한다면 실제 발화와 일치하는지 표본을 확인합니다.",
        "대사 외에 의미 있는 소리(경고음·화자 전환)가 자막에 반영됐는지 확인합니다.",
        "운영 단계에서 새 영상이 올라올 때 자막을 붙이는 담당과 절차가 있는지 확인합니다.",
      ],
      en: [
        "List the prerecorded and live media published in the product.",
        "If automatic captions are used, sample them against the actual speech.",
        "Confirm meaningful non-speech sound is captioned, including alerts and speaker changes.",
        "Confirm who adds captions when new media is published after launch.",
      ],
    },
    evidence: {
      ko: "영상 목록, 자막 제공 방식과 담당, 미제공 항목의 처리 계획을 메모에 남깁니다.",
      en: "Record the media list, how captions are produced, the owner, and a plan for anything missing.",
    },
    axis: "dynamic-status",
    roles: ["planning"],
    phases: ["planning", "implementation", "operation"],
    featureFlags: ["media_prerecorded", "media_live"],
    sourceUrl: src,
  },
  {
    id: "kwcag-3",
    standard: "kwcag-2.2",
    criterion: "3",
    level: null,
    title: { ko: "표의 구성", en: "Table structure" },
    question: {
      ko: "데이터 표에 제목 셀과 요약이 있고, 셀과 제목의 관계를 보조기술이 알 수 있나요?",
      en: "Do data tables expose header cells and the relationship between cells and headers?",
    },
    howToCheck: {
      ko: [
        "표가 데이터 표인지 레이아웃용인지 먼저 구분합니다. 레이아웃에는 표를 쓰지 않습니다.",
        "th, scope, caption 이 실제 구조와 맞는지 확인합니다.",
        "병합 셀이나 2단 헤더가 있으면 headers·id 로 관계를 명시했는지 확인합니다.",
      ],
      en: [
        "Separate data tables from layout tables. Layout should not use table markup.",
        "Confirm th, scope, and caption match the real structure.",
        "Where cells are merged or headers are two levels deep, confirm headers and id connect them.",
      ],
    },
    evidence: {
      ko: "검사한 표의 위치, 헤더 구조, 수정한 마크업을 메모에 남깁니다.",
      en: "Record where each table lives, its header structure, and the markup you changed.",
    },
    axis: "structure-semantics",
    roles: ["planning", "publishing"],
    phases: ["implementation", "qa"],
    featureFlags: ["data_tables"],
    sourceUrl: src,
    relatedTool: "html-accessibility-checker",
  },
  {
    id: "kwcag-4",
    standard: "kwcag-2.2",
    criterion: "4",
    level: null,
    title: { ko: "콘텐츠의 선형 구조", en: "Linear structure of content" },
    question: {
      ko: "CSS 를 끄거나 DOM 순서로 읽었을 때 콘텐츠가 의미 있는 순서로 이어지나요?",
      en: "Does the content still read in a meaningful order when CSS is removed or DOM order is followed?",
    },
    howToCheck: {
      ko: [
        "브라우저에서 스타일을 끈 상태로 문서를 위에서 아래로 읽어 봅니다.",
        "flex 의 order, grid 배치, absolute 위치 때문에 시각 순서와 DOM 순서가 달라진 영역을 찾습니다.",
        "탭 이동 순서가 화면에서 읽는 순서와 같은지 확인합니다.",
      ],
      en: [
        "Read the document top to bottom with author styles disabled.",
        "Find places where flex order, grid placement, or absolute positioning separate visual order from DOM order.",
        "Confirm the tab sequence matches the reading sequence on screen.",
      ],
    },
    evidence: {
      ko: "순서가 어긋난 컴포넌트와 DOM 을 어떻게 재배치했는지 메모에 남깁니다.",
      en: "Record which components were out of order and how the DOM was rearranged.",
    },
    axis: "structure-semantics",
    roles: ["design", "publishing"],
    phases: ["design", "implementation"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "html-accessibility-checker",
  },
  {
    id: "kwcag-5",
    standard: "kwcag-2.2",
    criterion: "5",
    level: null,
    title: { ko: "명확한 지시사항 제공", en: "Clear instructions" },
    question: {
      ko: "안내 문구가 모양·위치·색·소리에만 의존하지 않고 글로도 이해되나요?",
      en: "Do instructions work without relying on shape, position, color, or sound alone?",
    },
    howToCheck: {
      ko: [
        "\"오른쪽 버튼\", \"파란 항목\", \"아래 동그라미\" 같은 감각 의존 표현을 검색합니다.",
        "해당 문구에 이름·레이블·순서 같은 다른 단서를 함께 제공했는지 확인합니다.",
        "도움말·툴팁·오류 안내도 같은 기준으로 확인합니다.",
      ],
      en: [
        "Search the copy for sensory-only references such as the right button, the blue item, or the circle below.",
        "Confirm each one also names the control, its label, or its position in a sequence.",
        "Apply the same check to help text, tooltips, and error messages.",
      ],
    },
    evidence: {
      ko: "수정한 문구와 새 표현을 메모에 남깁니다.",
      en: "Record the sentences you rewrote and the wording you replaced them with.",
    },
    axis: "cognitive-process",
    roles: ["planning", "design"],
    phases: ["planning", "design", "qa"],
    featureFlags: [],
    sourceUrl: src,
  },
  {
    id: "kwcag-6",
    standard: "kwcag-2.2",
    criterion: "6",
    level: null,
    title: { ko: "색에 무관한 콘텐츠 인식", en: "Content recognition without color" },
    question: {
      ko: "색만으로 구분되는 정보가 없고, 모든 상태에 색 외의 단서가 함께 있나요?",
      en: "Is every piece of information distinguishable without relying on color alone?",
    },
    howToCheck: {
      ko: [
        "상태 배지, 그래프 범례, 필수 표시, 유효성 오류, 링크 구분을 목록으로 모읍니다.",
        "각 항목에 텍스트·아이콘·밑줄·패턴 중 하나 이상이 함께 있는지 확인합니다.",
        "색각이상 시뮬레이터로 시안을 변환해 구분이 사라지는 조합을 찾습니다.",
      ],
      en: [
        "List status badges, chart legends, required markers, validation errors, and link styling.",
        "Confirm each one also uses text, an icon, an underline, or a pattern.",
        "Run the design through the color blindness simulator to find pairs that stop being distinguishable.",
      ],
    },
    evidence: {
      ko: "확인한 색 조합, 추가한 비색상 단서, 남은 이슈를 메모에 남깁니다.",
      en: "Record the color pairs reviewed, the non-color cues you added, and anything still open.",
    },
    axis: "color",
    roles: ["design"],
    phases: ["design", "qa"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "color-blindness-simulator",
  },
  {
    id: "kwcag-7",
    standard: "kwcag-2.2",
    criterion: "7",
    level: null,
    title: { ko: "자동 재생 금지", en: "No automatic audio playback" },
    question: {
      ko: "페이지 진입 시 자동으로 소리가 나지 않거나, 3초 이내에 멈추거나 끌 수 있나요?",
      en: "Does the page avoid auto-playing sound, or stop it within three seconds with a way to turn it off?",
    },
    howToCheck: {
      ko: [
        "페이지 진입 직후 소리가 나는 배경 음악·영상·광고 위젯이 있는지 확인합니다.",
        "자동 재생이 필요하다면 즉시 접근할 수 있는 정지·음소거 컨트롤이 있는지 확인합니다.",
        "외부 임베드와 광고 스크립트도 같은 기준으로 확인합니다.",
      ],
      en: [
        "Check for background audio, video, or ad widgets that make sound on load.",
        "If autoplay is required, confirm a pause or mute control is reachable immediately.",
        "Apply the same check to embedded third-party content and ad scripts.",
      ],
    },
    evidence: {
      ko: "자동 재생 요소의 위치와 제어 방법, 제거 여부를 메모에 남깁니다.",
      en: "Record where autoplay occurs, how it can be controlled, and whether it was removed.",
    },
    axis: "dynamic-status",
    roles: ["planning", "publishing"],
    phases: ["implementation", "qa", "operation"],
    featureFlags: ["moving_content", "media_prerecorded"],
    sourceUrl: src,
  },
  {
    id: "kwcag-8",
    standard: "kwcag-2.2",
    criterion: "8",
    level: null,
    title: { ko: "텍스트 콘텐츠의 명도 대비", en: "Contrast of text content" },
    question: {
      ko: "일반 텍스트와 배경의 대비가 4.5:1 이상이며, 예외 조건을 구분해 확인했나요?",
      en: "Is text contrast at least 4.5:1, with the documented exceptions checked separately?",
    },
    howToCheck: {
      ko: [
        "본문·버튼·입력 안내·플레이스홀더 등 실제 사용 색상 조합을 수집합니다.",
        "명도대비 검사기로 기준별 결과를 확인합니다.",
        "굵은 18.5px 이상 또는 24px 이상은 3:1 예외가 적용되는지 개별로 판단합니다.",
        "이미지·그라디언트 위 텍스트는 가장 밝은 지점과 가장 어두운 지점을 각각 측정합니다.",
      ],
      en: [
        "Collect the real color pairs in use: body text, buttons, hints, and placeholders.",
        "Measure each pair with the contrast checker.",
        "Decide case by case whether the 3:1 large-text exception applies.",
        "For text over images or gradients, measure the lightest and darkest points behind it.",
      ],
    },
    evidence: {
      ko: "검사한 색상 조합, 대비 비율, 수정된 디자인 링크를 메모에 남깁니다.",
      en: "Record the color pairs tested, their ratios, and a link to the corrected design.",
    },
    axis: "color",
    roles: ["design"],
    phases: ["design", "qa"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "color-contrast-checker",
  },
  {
    id: "kwcag-9",
    standard: "kwcag-2.2",
    criterion: "9",
    level: null,
    title: { ko: "콘텐츠 간의 구분", en: "Distinction between content" },
    question: {
      ko: "이웃한 콘텐츠 영역이 테두리·간격·배경 등으로 시각적으로 구분되나요?",
      en: "Are adjacent content regions visually distinguishable by border, spacing, or background?",
    },
    howToCheck: {
      ko: [
        "카드·섹션·목록 항목의 경계가 색 하나에만 의존하지 않는지 확인합니다.",
        "구분선·간격·배경 차이 중 하나 이상이 실제로 보이는지 확인합니다.",
        "경계선 색만 쓴다면 인접 배경과의 대비가 3:1 이상인지 측정합니다.",
      ],
      en: [
        "Check whether card, section, and list boundaries depend on a single color.",
        "Confirm at least one of border, spacing, or background difference is actually visible.",
        "Where only a border color separates regions, measure it against the adjacent background for 3:1.",
      ],
    },
    evidence: {
      ko: "구분이 약한 영역과 적용한 해결 방법을 메모에 남깁니다.",
      en: "Record the regions with weak separation and the fix you applied.",
    },
    axis: "color",
    roles: ["design"],
    phases: ["design", "qa"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "color-contrast-checker",
  },
  {
    id: "kwcag-10",
    standard: "kwcag-2.2",
    criterion: "10",
    level: null,
    title: { ko: "키보드 사용 보장", en: "Keyboard accessibility" },
    question: {
      ko: "마우스 없이 키보드만으로 모든 기능을 실행하고 어디서든 빠져나올 수 있나요?",
      en: "Can every function be operated with the keyboard alone, with no place that traps focus?",
    },
    howToCheck: {
      ko: [
        "주요 과업을 처음부터 끝까지 Tab·Shift+Tab·Enter·Space·방향키만으로 수행합니다.",
        "모달, 드롭다운, 날짜 선택기, 캐러셀에서 초점이 갇히지 않는지 확인합니다.",
        "div·span 에 클릭 핸들러만 붙은 가짜 버튼이 있는지 확인합니다.",
        "마우스 hover 로만 나타나는 메뉴가 키보드로도 열리는지 확인합니다.",
      ],
      en: [
        "Complete each key task using only Tab, Shift+Tab, Enter, Space, and arrow keys.",
        "Confirm dialogs, dropdowns, date pickers, and carousels never trap focus.",
        "Look for div or span elements that act as buttons with a click handler only.",
        "Confirm menus that appear on hover can also be opened from the keyboard.",
      ],
    },
    evidence: {
      ko: "테스트한 과업, 사용한 브라우저, 키보드로 막힌 지점을 메모에 남깁니다.",
      en: "Record the tasks tested, the browser used, and every point where the keyboard got stuck.",
    },
    axis: "keyboard-focus",
    roles: ["publishing"],
    phases: ["implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
  },
  {
    id: "kwcag-11",
    standard: "kwcag-2.2",
    criterion: "11",
    level: null,
    title: { ko: "초점 이동과 표시", en: "Focus movement and indication" },
    question: {
      ko: "초점이 논리적인 순서로 이동하고, 현재 초점 위치가 가려지지 않고 분명히 보이나요?",
      en: "Does focus move in a logical order and stay clearly visible and unobscured?",
    },
    howToCheck: {
      ko: [
        "Tab 을 눌러 이동하는 순서가 화면에서 읽는 순서와 같은지 확인합니다.",
        "outline: none 으로 초점 표시를 지운 뒤 대체 표시를 넣지 않은 곳이 있는지 검색합니다.",
        "sticky 헤더·하단 바·쿠키 배너가 초점 요소를 가리지 않는지 확인합니다.",
        "모달을 열고 닫은 뒤 초점이 원래 위치로 돌아오는지 확인합니다.",
      ],
      en: [
        "Tab through the page and compare the focus order with the visual reading order.",
        "Search for outline: none without a replacement focus style.",
        "Confirm sticky headers, bottom bars, and cookie banners never cover the focused element.",
        "Confirm focus returns to the trigger after a dialog closes.",
      ],
    },
    evidence: {
      ko: "초점 순서가 어긋난 화면, 초점 스타일 규칙, 가림이 발생한 컴포넌트를 메모에 남깁니다.",
      en: "Record screens with a broken focus order, the focus style rule, and any component that obscured focus.",
    },
    axis: "keyboard-focus",
    roles: ["design", "publishing"],
    phases: ["design", "implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "html-accessibility-checker",
  },
  {
    id: "kwcag-12",
    standard: "kwcag-2.2",
    criterion: "12",
    level: null,
    title: { ko: "조작 가능", en: "Operable controls" },
    question: {
      ko: "버튼·링크 같은 조작 요소가 충분히 크고, 서로 겹치지 않을 만큼 떨어져 있나요?",
      en: "Are interactive controls large enough and spaced far enough apart to operate reliably?",
    },
    howToCheck: {
      ko: [
        "아이콘 버튼, 체크박스, 페이지네이션처럼 작은 컨트롤의 실제 클릭 영역을 측정합니다.",
        "모바일 화면에서 인접한 컨트롤 사이 간격이 충분한지 확인합니다.",
        "본문 안의 짧은 링크처럼 예외로 볼 수 있는 경우를 따로 기록합니다.",
      ],
      en: [
        "Measure the real hit area of small controls such as icon buttons, checkboxes, and pagination.",
        "Confirm adjacent controls are far enough apart on a phone-sized screen.",
        "Note the cases you treat as exceptions, such as short inline links inside a sentence.",
      ],
    },
    evidence: {
      ko: "측정한 컨트롤 크기와 간격, 조정한 값을 메모에 남깁니다.",
      en: "Record the measured control sizes and spacing, and the values you changed.",
    },
    axis: "target-pointer",
    roles: ["design", "publishing"],
    phases: ["design", "implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
  },
  {
    id: "kwcag-13",
    standard: "kwcag-2.2",
    criterion: "13",
    level: null,
    title: { ko: "문자 단축키", en: "Character key shortcuts" },
    question: {
      ko: "한 글자 단축키가 있다면 끄거나 바꾸거나 초점이 있을 때만 동작하게 할 수 있나요?",
      en: "If single-character shortcuts exist, can they be turned off, remapped, or limited to focus?",
    },
    howToCheck: {
      ko: [
        "코드에서 keydown·keypress 핸들러를 찾아 수식키 없는 한 글자 단축키를 확인합니다.",
        "검색·에디터·플레이어처럼 단축키를 많이 쓰는 화면을 우선 확인합니다.",
        "해당 단축키를 끄거나 재설정할 수 있는 설정이 있는지 확인합니다.",
      ],
      en: [
        "Search keydown and keypress handlers for single-character shortcuts without a modifier.",
        "Start with screens that rely on shortcuts, such as search, editors, and players.",
        "Confirm a setting exists to disable or remap them.",
      ],
    },
    evidence: {
      ko: "발견한 단축키 목록과 끄기·재설정 방법을 메모에 남깁니다.",
      en: "Record the shortcuts found and how they can be disabled or remapped.",
    },
    axis: "keyboard-focus",
    roles: ["publishing"],
    phases: ["implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
  },
  {
    id: "kwcag-14",
    standard: "kwcag-2.2",
    criterion: "14",
    level: null,
    title: { ko: "응답시간 조절", en: "Adjustable response time" },
    question: {
      ko: "시간 제한이 있는 기능에서 사용자가 시간을 끄거나 조절하거나 연장할 수 있나요?",
      en: "Can users turn off, adjust, or extend any time limit in the product?",
    },
    howToCheck: {
      ko: [
        "세션 만료, 예약·결제 대기, 인증번호 유효시간, 자동 로그아웃을 목록으로 모읍니다.",
        "만료 전에 경고하고 연장할 수 있는 수단이 있는지 확인합니다.",
        "제한 시간이 보안·실시간 경매처럼 본질적인 경우인지 따로 판단합니다.",
      ],
      en: [
        "List session expiry, booking or payment holds, one-time code validity, and auto sign-out.",
        "Confirm users are warned before expiry and can extend the limit.",
        "Decide separately whether a limit is essential, as in a real-time auction.",
      ],
    },
    evidence: {
      ko: "시간 제한 목록, 경고 시점, 연장 방법을 메모에 남깁니다.",
      en: "Record each time limit, when the warning appears, and how it can be extended.",
    },
    axis: "cognitive-process",
    roles: ["planning", "publishing"],
    phases: ["planning", "implementation", "qa"],
    featureFlags: ["timed_content", "authentication"],
    sourceUrl: src,
  },
  {
    id: "kwcag-15",
    standard: "kwcag-2.2",
    criterion: "15",
    level: null,
    title: { ko: "정지 기능 제공", en: "Pause control" },
    question: {
      ko: "자동으로 움직이거나 갱신되는 콘텐츠를 멈추거나 숨길 수 있나요?",
      en: "Can moving or automatically updating content be paused, stopped, or hidden?",
    },
    howToCheck: {
      ko: [
        "캐러셀, 자동 슬라이드, 티커, 실시간 갱신 목록, 애니메이션 배너를 모읍니다.",
        "각 요소에 정지·숨김 컨트롤이 있고 키보드로 도달 가능한지 확인합니다.",
        "prefers-reduced-motion 설정에서 움직임이 줄어드는지 확인합니다.",
      ],
      en: [
        "List carousels, auto-advancing slides, tickers, live-updating lists, and animated banners.",
        "Confirm each has a pause or hide control that is reachable by keyboard.",
        "Confirm motion is reduced when prefers-reduced-motion is set.",
      ],
    },
    evidence: {
      ko: "움직이는 요소 목록과 제공한 정지 수단을 메모에 남깁니다.",
      en: "Record the moving elements and the pause mechanism provided for each.",
    },
    axis: "dynamic-status",
    roles: ["planning", "publishing"],
    phases: ["design", "implementation", "qa"],
    featureFlags: ["moving_content"],
    sourceUrl: src,
  },
  {
    id: "kwcag-16",
    standard: "kwcag-2.2",
    criterion: "16",
    level: null,
    title: { ko: "깜빡임과 번쩍임 사용 제한", en: "Limited use of flashing" },
    question: {
      ko: "1초에 3~4회를 넘는 깜빡임이나 번쩍임이 없나요?",
      en: "Is the page free of content that flashes more than three times per second?",
    },
    howToCheck: {
      ko: [
        "로딩 애니메이션, 강조 효과, 광고·영상 소재에 빠른 명멸이 있는지 확인합니다.",
        "외부에서 들어오는 배너·임베드도 같은 기준으로 확인합니다.",
        "불가피하면 해당 영역의 크기를 줄이고 사전 경고를 제공했는지 확인합니다.",
      ],
      en: [
        "Look for rapid flashing in loading animations, highlight effects, ads, and video assets.",
        "Apply the same check to third-party banners and embeds.",
        "Where unavoidable, confirm the area is small and a warning appears first.",
      ],
    },
    evidence: {
      ko: "검토한 애니메이션·소재와 판단 근거를 메모에 남깁니다.",
      en: "Record the animations and assets reviewed and the basis for your decision.",
    },
    axis: "dynamic-status",
    roles: ["design", "publishing"],
    phases: ["design", "qa", "operation"],
    featureFlags: [],
    sourceUrl: src,
  },
  {
    id: "kwcag-17",
    standard: "kwcag-2.2",
    criterion: "17",
    level: null,
    title: { ko: "반복 영역 건너뛰기", en: "Skip repetitive areas" },
    question: {
      ko: "헤더·내비게이션처럼 반복되는 영역을 건너뛰고 본문으로 갈 수단이 있나요?",
      en: "Is there a way to skip repeated blocks such as the header and navigation?",
    },
    howToCheck: {
      ko: [
        "페이지 첫 Tab 에서 본문 바로가기 링크가 나타나는지 확인합니다.",
        "바로가기를 눌렀을 때 초점이 실제로 본문으로 이동하는지 확인합니다.",
        "main, nav 같은 랜드마크로도 이동할 수 있게 구조화했는지 확인합니다.",
      ],
      en: [
        "Confirm a skip link appears on the first Tab press.",
        "Confirm activating it actually moves focus into the main content.",
        "Confirm landmarks such as main and nav give an alternative way to jump.",
      ],
    },
    evidence: {
      ko: "바로가기 링크 구현 위치와 동작 확인 결과를 메모에 남깁니다.",
      en: "Record where the skip link is implemented and the result of testing it.",
    },
    axis: "keyboard-focus",
    roles: ["publishing"],
    phases: ["implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "html-accessibility-checker",
  },
  {
    id: "kwcag-18",
    standard: "kwcag-2.2",
    criterion: "18",
    level: null,
    title: { ko: "제목 제공", en: "Titles and headings" },
    question: {
      ko: "페이지·프레임·콘텐츠 블록에 내용을 알 수 있는 제목이 있나요?",
      en: "Do pages, frames, and content blocks have titles that describe their content?",
    },
    howToCheck: {
      ko: [
        "각 페이지의 title 이 서로 다르고 페이지 내용을 설명하는지 확인합니다.",
        "h1~h6 이 시각적 크기가 아니라 문서 구조를 따르는지, 단계 건너뜀이 없는지 확인합니다.",
        "iframe 에 title 속성이 있는지 확인합니다.",
      ],
      en: [
        "Confirm every page title is unique and describes the page.",
        "Confirm h1 to h6 follow document structure rather than visual size, with no skipped levels.",
        "Confirm each iframe has a title attribute.",
      ],
    },
    evidence: {
      ko: "제목 규칙, 수정한 헤딩 구조, 페이지 title 규칙을 메모에 남깁니다.",
      en: "Record the heading rules, the structure you fixed, and the page title convention.",
    },
    axis: "structure-semantics",
    roles: ["planning", "publishing"],
    phases: ["planning", "implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "html-accessibility-checker",
  },
  {
    id: "kwcag-19",
    standard: "kwcag-2.2",
    criterion: "19",
    level: null,
    title: { ko: "적절한 링크 텍스트", en: "Appropriate link text" },
    question: {
      ko: "링크 텍스트만 읽어도 어디로 가는지 알 수 있나요?",
      en: "Can the destination of each link be understood from its text alone?",
    },
    howToCheck: {
      ko: [
        "\"더보기\", \"클릭\", \"여기\" 같은 문구만 있는 링크를 검색합니다.",
        "아이콘만 있는 링크에 접근 가능한 이름이 있는지 확인합니다.",
        "같은 문구의 링크가 서로 다른 곳으로 간다면 구분할 수 있는 이름을 붙였는지 확인합니다.",
      ],
      en: [
        "Search for links whose text is only More, Click, or Here.",
        "Confirm icon-only links carry an accessible name.",
        "Where the same text points to different destinations, confirm each name is distinguishable.",
      ],
    },
    evidence: {
      ko: "수정한 링크 문구와 아이콘 링크의 이름 규칙을 메모에 남깁니다.",
      en: "Record the link text you rewrote and the naming rule for icon links.",
    },
    axis: "structure-semantics",
    roles: ["planning", "publishing"],
    phases: ["planning", "implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "html-accessibility-checker",
  },
  {
    id: "kwcag-20",
    standard: "kwcag-2.2",
    criterion: "20",
    level: null,
    title: { ko: "고정된 참조 위치 정보", en: "Fixed reference location information" },
    question: {
      ko: "전자출판문서에서 쪽 번호 같은 고정 참조 위치를 제공하고 유지하나요?",
      en: "Does the publication keep a stable reference location such as a page number?",
    },
    howToCheck: {
      ko: [
        "전자책·PDF 뷰어처럼 원본 인쇄본과 대조가 필요한 콘텐츠가 있는지 확인합니다.",
        "글자 크기나 화면 크기를 바꿔도 참조 위치가 유지되는지 확인합니다.",
        "인용·검색 기능이 같은 참조 위치를 사용하는지 확인합니다.",
      ],
      en: [
        "Check whether the product hosts publications that need to match a printed source.",
        "Confirm the reference location stays stable when font size or viewport changes.",
        "Confirm citation and search features use the same reference.",
      ],
    },
    evidence: {
      ko: "해당 콘텐츠 유형과 참조 위치 제공 방식을 메모에 남깁니다.",
      en: "Record the content type and how the reference location is provided.",
    },
    axis: "structure-semantics",
    roles: ["planning", "publishing"],
    phases: ["planning", "implementation"],
    featureFlags: ["epub_reference"],
    sourceUrl: src,
  },
  {
    id: "kwcag-21",
    standard: "kwcag-2.2",
    criterion: "21",
    level: null,
    title: { ko: "단일 포인터 입력 지원", en: "Single pointer input support" },
    question: {
      ko: "다중 손가락·경로 기반 제스처에 한 손가락으로 쓸 수 있는 대안이 있나요?",
      en: "Does every multipoint or path-based gesture have a single-pointer alternative?",
    },
    howToCheck: {
      ko: [
        "핀치 줌, 스와이프 삭제, 드래그 정렬, 서명·그리기 같은 제스처를 모읍니다.",
        "각 기능에 버튼·메뉴 같은 단순 탭 대안이 있는지 확인합니다.",
        "기기 자체의 확대 기능처럼 제품이 구현하지 않은 동작은 분리해 기록합니다.",
      ],
      en: [
        "List pinch zoom, swipe to delete, drag to reorder, and drawing or signature gestures.",
        "Confirm each has a simple tap alternative such as a button or menu.",
        "Separate gestures handled by the platform itself from those your product implements.",
      ],
    },
    evidence: {
      ko: "제스처 목록과 제공한 단일 포인터 대안을 메모에 남깁니다.",
      en: "Record each gesture and the single-pointer alternative provided.",
    },
    axis: "target-pointer",
    roles: ["planning", "publishing"],
    phases: ["planning", "implementation", "qa"],
    featureFlags: ["drag_gesture"],
    sourceUrl: src,
  },
  {
    id: "kwcag-22",
    standard: "kwcag-2.2",
    criterion: "22",
    level: null,
    title: { ko: "포인터 입력 취소", en: "Pointer cancellation" },
    question: {
      ko: "누른 뒤 손을 떼기 전에 밖으로 빼서 실행을 취소할 수 있나요?",
      en: "Can a pointer action be aborted by moving away before release?",
    },
    howToCheck: {
      ko: [
        "중요한 동작이 mousedown·touchstart 가 아니라 클릭·mouseup 에서 실행되는지 확인합니다.",
        "삭제·결제·전송처럼 되돌리기 어려운 동작을 우선 확인합니다.",
        "다운 이벤트에서 실행해야 한다면 취소·되돌리기 수단이 있는지 확인합니다.",
      ],
      en: [
        "Confirm important actions run on click or mouseup rather than mousedown or touchstart.",
        "Start with actions that are hard to undo: delete, pay, and send.",
        "If a down event must trigger the action, confirm an undo or cancel path exists.",
      ],
    },
    evidence: {
      ko: "확인한 이벤트 바인딩과 예외 처리 방식을 메모에 남깁니다.",
      en: "Record the event bindings reviewed and how exceptions are handled.",
    },
    axis: "target-pointer",
    roles: ["publishing"],
    phases: ["implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
  },
  {
    id: "kwcag-23",
    standard: "kwcag-2.2",
    criterion: "23",
    level: null,
    title: { ko: "레이블과 네임", en: "Label and name" },
    question: {
      ko: "화면에 보이는 컨트롤 문구가 접근 가능한 이름에도 포함되어 있나요?",
      en: "Does each control's accessible name contain the text shown on screen?",
    },
    howToCheck: {
      ko: [
        "버튼·링크의 보이는 문구와 aria-label 이 어긋난 곳을 찾습니다.",
        "aria-label 로 보이는 문구를 덮어써서 음성 명령이 실패할 수 있는 곳을 확인합니다.",
        "아이콘 + 텍스트 조합에서 텍스트가 이름 앞부분에 오는지 확인합니다.",
      ],
      en: [
        "Find buttons and links whose visible text differs from their aria-label.",
        "Look for aria-label values that hide the visible text and break voice control.",
        "Confirm the visible text comes first in the accessible name of icon plus text controls.",
      ],
    },
    evidence: {
      ko: "불일치한 컨트롤과 수정한 이름 값을 메모에 남깁니다.",
      en: "Record the mismatched controls and the accessible names you corrected.",
    },
    axis: "structure-semantics",
    roles: ["design", "publishing"],
    phases: ["design", "implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "html-accessibility-checker",
  },
  {
    id: "kwcag-24",
    standard: "kwcag-2.2",
    criterion: "24",
    level: null,
    title: { ko: "동작 기반 작동", en: "Motion actuation" },
    question: {
      ko: "기기를 흔들거나 기울여 실행하는 기능에 일반 컨트롤 대안이 있고 끌 수 있나요?",
      en: "Can motion-triggered features also be operated by a standard control and be turned off?",
    },
    howToCheck: {
      ko: [
        "흔들어서 되돌리기, 기울여 넘기기, 걸음 수 같은 센서 기반 기능을 모읍니다.",
        "각 기능에 버튼·메뉴 대안이 있는지 확인합니다.",
        "의도치 않은 동작을 막기 위해 센서 반응을 끌 수 있는지 확인합니다.",
      ],
      en: [
        "List sensor-driven features such as shake to undo, tilt to navigate, and step detection.",
        "Confirm each has a button or menu alternative.",
        "Confirm the motion response can be disabled to prevent accidental activation.",
      ],
    },
    evidence: {
      ko: "센서 기반 기능과 대안 컨트롤, 끄기 설정 위치를 메모에 남깁니다.",
      en: "Record the motion features, their alternative controls, and where they can be disabled.",
    },
    axis: "target-pointer",
    roles: ["planning", "publishing"],
    phases: ["planning", "implementation"],
    featureFlags: ["motion_input"],
    sourceUrl: src,
  },
  {
    id: "kwcag-25",
    standard: "kwcag-2.2",
    criterion: "25",
    level: null,
    title: { ko: "기본 언어 표시", en: "Default language declaration" },
    question: {
      ko: "각 페이지의 기본 언어가 html lang 에 선언되어 있나요?",
      en: "Is the default human language declared on the html element of every page?",
    },
    howToCheck: {
      ko: [
        "국문 페이지는 lang=\"ko\", 영문 페이지는 lang=\"en\" 으로 서버 렌더 결과에서 확인합니다.",
        "언어 전환 기능이 있다면 전환 후 lang 값도 함께 바뀌는지 확인합니다.",
        "본문 중간에 다른 언어 구절이 길게 들어가면 해당 요소에 lang 을 붙였는지 확인합니다.",
      ],
      en: [
        "Check the server-rendered HTML for lang=\"ko\" or lang=\"en\" on the html element.",
        "If a language switch exists, confirm the lang value changes with it.",
        "Where a long passage uses another language, confirm that element carries its own lang.",
      ],
    },
    evidence: {
      ko: "확인한 URL 과 lang 값, 수정 여부를 메모에 남깁니다.",
      en: "Record the URLs checked, the lang values found, and what you changed.",
    },
    axis: "structure-semantics",
    roles: ["publishing"],
    phases: ["implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "html-accessibility-checker",
  },
  {
    id: "kwcag-26",
    standard: "kwcag-2.2",
    criterion: "26",
    level: null,
    title: { ko: "사용자 요구에 따른 실행", en: "Execution on user request" },
    question: {
      ko: "사용자가 의도하지 않은 맥락 변화(자동 이동·자동 제출·새 창)가 없나요?",
      en: "Does the product avoid changes of context the user did not request?",
    },
    howToCheck: {
      ko: [
        "입력 중 초점 이동이나 자동 제출이 일어나는 폼이 있는지 확인합니다.",
        "선택만 해도 페이지가 이동하는 드롭다운이 있는지 확인합니다.",
        "새 창·새 탭으로 열리는 링크에 사전 안내가 있는지 확인합니다.",
      ],
      en: [
        "Look for forms that move focus or submit automatically while typing.",
        "Look for select elements that navigate on change alone.",
        "Confirm links that open a new window or tab say so in advance.",
      ],
    },
    evidence: {
      ko: "자동 실행이 있던 지점과 변경한 동작을 메모에 남깁니다.",
      en: "Record where automatic changes occurred and the behavior you changed.",
    },
    axis: "cognitive-process",
    roles: ["planning", "publishing"],
    phases: ["planning", "implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
  },
  {
    id: "kwcag-27",
    standard: "kwcag-2.2",
    criterion: "27",
    level: null,
    title: { ko: "찾기 쉬운 도움 정보", en: "Consistent help" },
    question: {
      ko: "도움말·문의 수단이 여러 페이지에서 같은 위치에 일관되게 있나요?",
      en: "Does help appear in the same relative place across pages that provide it?",
    },
    howToCheck: {
      ko: [
        "고객센터, 챗봇, 연락처, 도움말 링크가 어느 페이지에 있는지 목록으로 만듭니다.",
        "여러 페이지에서 같은 상대 위치(헤더·푸터 등)에 나오는지 확인합니다.",
        "도움 수단이 페이지마다 다른 이름으로 불리지 않는지 확인합니다.",
      ],
      en: [
        "List where the help center, chat, contact details, and help links appear.",
        "Confirm they occupy the same relative position across those pages.",
        "Confirm the same help mechanism is not renamed from page to page.",
      ],
    },
    evidence: {
      ko: "도움 수단의 위치 규칙과 예외 페이지를 메모에 남깁니다.",
      en: "Record the placement rule for help and any page that deviates.",
    },
    axis: "cognitive-process",
    roles: ["planning", "design"],
    phases: ["planning", "design"],
    featureFlags: [],
    sourceUrl: src,
  },
  {
    id: "kwcag-28",
    standard: "kwcag-2.2",
    criterion: "28",
    level: null,
    title: { ko: "오류 정정", en: "Error correction" },
    question: {
      ko: "입력 오류를 글로 알려주고, 어디를 어떻게 고쳐야 하는지 안내하나요?",
      en: "Are input errors described in text with guidance on how to fix them?",
    },
    howToCheck: {
      ko: [
        "빈 필수값, 잘못된 형식, 서버 거절 등 오류 상황을 실제로 발생시켜 봅니다.",
        "오류 문구가 어떤 필드의 무엇이 문제인지 구체적으로 말하는지 확인합니다.",
        "오류 발생 시 초점이 문제 지점으로 이동하거나 보조기술에 전달되는지 확인합니다.",
        "되돌리기 어려운 제출에는 확인·수정·취소 단계가 있는지 확인합니다.",
      ],
      en: [
        "Trigger real errors: empty required fields, wrong formats, and server rejections.",
        "Confirm each message names the field and what is wrong with it.",
        "Confirm focus moves to the problem or the error is announced to assistive technology.",
        "For irreversible submissions, confirm a review, correct, or cancel step exists.",
      ],
    },
    evidence: {
      ko: "재현한 오류, 화면 문구, 초점 처리 방식을 메모에 남깁니다.",
      en: "Record the errors reproduced, the messages shown, and how focus was handled.",
    },
    axis: "dynamic-status",
    roles: ["planning", "publishing"],
    phases: ["planning", "implementation", "qa"],
    featureFlags: ["forms"],
    sourceUrl: src,
  },
  {
    id: "kwcag-29",
    standard: "kwcag-2.2",
    criterion: "29",
    level: null,
    title: { ko: "레이블 제공", en: "Labels" },
    question: {
      ko: "모든 입력 요소에 용도를 알 수 있는 레이블이 프로그래밍적으로 연결돼 있나요?",
      en: "Is every input programmatically associated with a label that explains its purpose?",
    },
    howToCheck: {
      ko: [
        "label for 와 input id 가 실제로 연결돼 있는지 확인합니다.",
        "플레이스홀더만으로 레이블을 대신한 필드가 있는지 확인합니다.",
        "라디오·체크박스 묶음에 fieldset 과 legend 로 그룹 이름을 줬는지 확인합니다.",
        "필수 여부와 입력 형식 안내가 레이블 또는 설명으로 제공되는지 확인합니다.",
      ],
      en: [
        "Confirm label for and input id are actually connected.",
        "Find fields that use a placeholder instead of a label.",
        "Confirm radio and checkbox groups are named with fieldset and legend.",
        "Confirm required state and format hints are available as label or description text.",
      ],
    },
    evidence: {
      ko: "레이블이 없던 필드와 연결 방식, 그룹 이름 규칙을 메모에 남깁니다.",
      en: "Record the unlabeled fields, how you associated labels, and the grouping convention.",
    },
    axis: "structure-semantics",
    roles: ["design", "publishing"],
    phases: ["design", "implementation", "qa"],
    featureFlags: ["forms"],
    sourceUrl: src,
    relatedTool: "html-accessibility-checker",
  },
  {
    id: "kwcag-30",
    standard: "kwcag-2.2",
    criterion: "30",
    level: null,
    title: { ko: "접근 가능한 인증", en: "Accessible authentication" },
    question: {
      ko: "로그인·본인 확인에서 기억이나 글자 옮겨쓰기에만 의존하지 않는 방법이 있나요?",
      en: "Does authentication avoid depending on memory or transcription alone?",
    },
    howToCheck: {
      ko: [
        "로그인, 비밀번호 재설정, 본인 인증, 결제 승인 단계를 각각 확인합니다.",
        "비밀번호 붙여넣기와 브라우저 자동완성을 막고 있지 않은지 확인합니다.",
        "이미지·음성 인식 문제를 요구한다면 다른 대안이 함께 있는지 확인합니다.",
        "인증번호 입력에 충분한 시간과 재발송 수단이 있는지 확인합니다.",
      ],
      en: [
        "Review sign-in, password reset, identity verification, and payment approval separately.",
        "Confirm password paste and browser autofill are not blocked.",
        "If an image or audio puzzle is required, confirm an alternative method exists.",
        "Confirm one-time codes allow enough time and can be resent.",
      ],
    },
    evidence: {
      ko: "인증 단계별 방식, 대안 수단, 차단된 기능 여부를 메모에 남깁니다.",
      en: "Record each authentication step, the alternatives offered, and anything that is blocked.",
    },
    axis: "cognitive-process",
    roles: ["planning", "publishing"],
    phases: ["planning", "implementation", "qa"],
    featureFlags: ["authentication"],
    sourceUrl: src,
  },
  {
    id: "kwcag-31",
    standard: "kwcag-2.2",
    criterion: "31",
    level: null,
    title: { ko: "반복 입력 정보", en: "Redundant entry" },
    question: {
      ko: "같은 절차 안에서 이미 입력한 정보를 다시 입력하게 하지 않나요?",
      en: "Does the product avoid asking for the same information twice in one process?",
    },
    howToCheck: {
      ko: [
        "여러 단계로 나뉜 가입·주문·신청 절차를 처음부터 끝까지 진행합니다.",
        "이전 단계 값이 자동으로 채워지거나 선택할 수 있게 제공되는지 확인합니다.",
        "보안상 재확인이 필요한 경우인지 따로 구분해 기록합니다.",
      ],
      en: [
        "Walk through each multi-step sign-up, order, or application flow end to end.",
        "Confirm earlier answers are prefilled or offered for selection.",
        "Note separately where re-entry is required for security reasons.",
      ],
    },
    evidence: {
      ko: "반복 입력이 있던 단계와 개선 방법, 보안 예외를 메모에 남깁니다.",
      en: "Record the steps that asked twice, how you fixed them, and any security exception.",
    },
    axis: "cognitive-process",
    roles: ["planning", "publishing"],
    phases: ["planning", "implementation"],
    featureFlags: ["forms", "authentication"],
    sourceUrl: src,
  },
  {
    id: "kwcag-32",
    standard: "kwcag-2.2",
    criterion: "32",
    level: null,
    title: { ko: "마크업 오류 방지", en: "Markup error prevention" },
    question: {
      ko: "요소 중첩, 중복 id, 속성 오류처럼 보조기술 해석을 방해하는 마크업 오류가 없나요?",
      en: "Is the markup free of nesting errors, duplicate ids, and attribute mistakes?",
    },
    howToCheck: {
      ko: [
        "실제 렌더링된 HTML 을 검사해 열고 닫는 태그가 맞는지 확인합니다.",
        "한 페이지 안에 중복된 id 가 있는지 확인합니다.",
        "aria-labelledby, aria-controls 가 존재하지 않는 id 를 가리키지 않는지 확인합니다.",
      ],
      en: [
        "Validate the rendered HTML for correctly opened and closed elements.",
        "Check for duplicate ids within a single page.",
        "Confirm aria-labelledby and aria-controls point at ids that exist.",
      ],
    },
    evidence: {
      ko: "검사한 페이지, 발견한 오류 유형, 수정 커밋을 메모에 남깁니다.",
      en: "Record the pages validated, the error types found, and the fix commit.",
    },
    axis: "structure-semantics",
    roles: ["publishing"],
    phases: ["implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
    relatedTool: "html-accessibility-checker",
  },
  {
    id: "kwcag-33",
    standard: "kwcag-2.2",
    criterion: "33",
    level: null,
    title: { ko: "웹 애플리케이션 접근성 준수", en: "Web application accessibility" },
    question: {
      ko: "직접 만든 위젯과 내장한 외부 콘텐츠가 이름·역할·값·상태를 올바르게 전달하나요?",
      en: "Do custom widgets and embedded third-party content expose correct name, role, value, and state?",
    },
    howToCheck: {
      ko: [
        "탭, 아코디언, 모달, 자동완성, 트리처럼 직접 구현한 컴포넌트를 모읍니다.",
        "각 컴포넌트의 role 과 aria 상태(expanded·selected·checked)가 실제 화면과 맞는지 확인합니다.",
        "지도·결제·에디터처럼 외부에서 들어온 컴포넌트의 접근성 지원 범위를 확인합니다.",
        "스크린리더로 주요 컴포넌트를 한 번씩 조작해 봅니다.",
      ],
      en: [
        "List the custom components you built: tabs, accordions, dialogs, comboboxes, trees.",
        "Confirm role and aria state such as expanded, selected, and checked match what is on screen.",
        "Check what accessibility support embedded third-party components actually provide.",
        "Operate each major component once with a screen reader.",
      ],
    },
    evidence: {
      ko: "컴포넌트 목록, 사용한 보조기술과 버전, 남은 이슈를 메모에 남깁니다.",
      en: "Record the component list, the assistive technology and version used, and open issues.",
    },
    axis: "dynamic-status",
    roles: ["publishing"],
    phases: ["implementation", "qa"],
    featureFlags: [],
    sourceUrl: src,
  },
];
